export const userLoginConstants={
    LOGIN_REQUEST:'LOGIN_REQUEST',
    LOGIN_FAILURE:'LOGIN_FAILURE',
    LOGIN_SUCCESS:'LOGIN_SUCCESS',
    LOGOUT_REQUEST:'LOGOUT_REQUEST',
}
export const userUpdateConstants = {
    UPDATE_REQUEST:'UPDATE_REQUEST',
    UPDATE_FAILURE:'UPDATE_FAILURE',
    UPDATE_SUCCESS:'UPDATE_SUCCESS',  
}

export const adminGetProductByIdConstants = {
    ADMIN_GET_PRODUCT_BY_ID_REQUEST: "ADMIN_GET_PRODUCT_BY_ID_REQUEST",
    ADMIN_GET_PRODUCT_BY_ID_SUCCESS: "ADMIN_GET_PRODUCT_BY_ID_SUCCESS",
    ADMIN_GET_PRODUCT_BY_ID_FAILURE: "ADMIN_GET_PRODUCT_BY_ID_FAILURE",
  };
  
//   export const adminUpdateProductConstants = {
//     ADMIN_UPDATE_PRODUCT_REQUEST: "ADMIN_UPDATE_PRODUCT_REQUEST",
//     ADMIN_UPDATE_PRODUCT_SUCCESS: "ADMIN_UPDATE_PRODUCT_SUCCESS",
//     ADMIN_UPDATE_PRODUCT_FAILURE: "ADMIN_UPDATE_PRODUCT_FAILURE",
//   };
  

// Constants for AdminGetGiftBoxById
export const adminGetGiftBoxByIdConstants = {
    ADMIN_GET_GIFT_BOX_BY_ID_REQUEST: 'ADMIN_GET_GIFT_BOX_BY_ID_REQUEST',
    ADMIN_GET_GIFT_BOX_BY_ID_SUCCESS: 'ADMIN_GET_GIFT_BOX_BY_ID_SUCCESS',
    ADMIN_GET_GIFT_BOX_BY_ID_FAILURE: 'ADMIN_GET_GIFT_BOX_BY_ID_FAILURE',
  };
  
  // Constants for AdminUpdateGiftBox
  export const adminUpdateGiftBoxConstants = {
    ADMIN_UPDATE_GIFT_BOX_REQUEST: 'ADMIN_UPDATE_GIFT_BOX_REQUEST',
    ADMIN_UPDATE_GIFT_BOX_SUCCESS: 'ADMIN_UPDATE_GIFT_BOX_SUCCESS',
    ADMIN_UPDATE_GIFT_BOX_FAILURE: 'ADMIN_UPDATE_GIFT_BOX_FAILURE',
  };
  

export const adminEditProductConstants = {
    ADMIN_EDITPRODUCT_REQUEST: "ADMIN_EDITPRODUCT_REQUEST",
    ADMIN_EDITPRODUCT_SUCCESS: "ADMIN_EDITPRODUCT_SUCCESS",
    ADMIN_EDITPRODUCT_FAILURE: "ADMIN_EDITPRODUCT_FAILURE",
  };
  

export const emailConstants = {
    EMAIL_REQUEST:'EMAIL_REQUEST',
    EMAIL_FAILURE:'EMAIL_FAILURE',
    EMAIL_SUCCESS:'EMAIL_SUCCESS',  
}

export const otpConstants = {
    OTP_REQUEST:'OTP_REQUEST',
    OTP_FAILURE:'OTP_FAILURE',
    OTP_SUCCESS:'OTP_SUCCESS',  
}

export const adminCreateProductConstants = {
    ADMIN_CREATEPRODUCT_REQUEST:'ADMIN_CREATEPRODUCT_REQUEST',
    ADMIN_CREATEPRODUCT_FAILURE:'ADMIN_CREATEPRODUCT_FAILURE',
    ADMIN_CREATEPRODUCT_SUCCESS:'ADMIN_CREATEPRODUCT_SUCCESS',    
}
export const adminCreateCategoryConstants = {
    ADMIN_CREATEPRODUCT_REQUEST:'ADMIN_CREATECATEGORY_REQUEST',
    ADMIN_CREATEPRODUCT_FAILURE:'ADMIN_CREATECATEGORY_FAILURE',
    ADMIN_CREATEPRODUCT_SUCCESS:'ADMIN_CREATECATEGORY_SUCCESS',    
}
export const adminUpdateProductConstants = {
    ADMIN_UPDATEPRODUCT_REQUEST:'ADMIN_UPDATEPRODUCT_REQUEST',
    ADMIN_UPDATEPRODUCT_FAILURE:'ADMIN_UPDATEPRODUCT_FAILURE',
    ADMIN_UPDATEPRODUCT_SUCCESS:'ADMIN_UPDATEPRODUCT_SUCCESS',    
}
export const adminUpdateCategoryConstants = {
    ADMIN_UPDATECATEGORY_REQUEST:'ADMIN_UPDATECATEGORY_REQUEST',
    ADMIN_UPDATECATEGORY_FAILURE:'ADMIN_UPDATECATEGORY_FAILURE',
    ADMIN_UPDATECATEGORY_SUCCESS:'ADMIN_UPDATECATEGORY_SUCCESS',    
}

export const adminRecentOrderConstants = {
    ADMIN_RECENTORDER_REQUEST:'ADMIN_RECENTORDER_REQUEST',
    ADMIN_RECENTORDER_FAILURE:'ADMIN_RECENTORDER_FAILURE',
    ADMIN_RECENTORDER_SUCCESS:'ADMIN_RECENTORDER_SUCCESS',    
}

export const adminGetUserInfoConstants = {
    ADMIN_USER_INFO_REQUEST:'ADMIN_USER_INFO_REQUEST',
    ADMIN_USER_INFO_FAILURE:'ADMIN_USER_INFO_FAILURE',
    ADMIN_USER_INFO_SUCCESS:'ADMIN_USER_INFO_SUCCESS',    
}

export const adminDeleteRecentOrderConstants = {
    ADMIN_DELETE_RECENT_ORDER_REQUEST:'ADMIN_DELETE_RECENT_ORDER_REQUEST',
    ADMIN_DELETE_RECENT_ORDER_FAILURE:'ADMIN_DELETE_RECENT_ORDER_FAILURE',
    ADMIN_DELETE_RECENT_ORDER_SUCCESS:'ADMIN_DELETE_RECENT_ORDER_SUCCESS',    
}

export const adminDeleteCustomerConstants = {
    ADMIN_DELETE_CUSTOMER_REQUEST:'ADMIN_DELETE_CUSTOMER_REQUEST',
    ADMIN_DELETE_CUSTOMER_FAILURE:'ADMIN_DELETE_CUSTOMER_FAILURE',
    ADMIN_DELETE_CUSTOMER_SUCCESS:'ADMIN_DELETE_CUSTOMER_SUCCESS',    
}

export const adminDeleteProductConstants = {
    ADMIN_DELETE_PRODUCT_REQUEST:'ADMIN_DELETE_PRODUCT_REQUEST',
    ADMIN_DELETE_PRODUCT_FAILURE:'ADMIN_DELETE_PRODUCT_FAILURE',
    ADMIN_DELETE_PRODUCT_SUCCESS:'ADMIN_DELETE_PRODUCT_SUCCESS',    
}

export const adminDeleteCategoryConstants = {
    ADMIN_DELETE_CATEGORY_REQUEST:'ADMIN_DELETE_CATEGORY_REQUEST',
    ADMIN_DELETE_CATEGORY_FAILURE:'ADMIN_DELETE_CATEGORY_FAILURE',
    ADMIN_DELETE_CATEGORY_SUCCESS:'ADMIN_DELETE_CATEGORY_SUCCESS',    
}

export const adminCustomersConstants = {
    ADMIN_CUSTOMERS_REQUEST:'ADMIN_CUSTOMERS_REQUEST',
    ADMIN_CUSTOMERS_FAILURE:'ADMIN_CUSTOMERS_FAILURE',
    ADMIN_CUSTOMERS_SUCCESS:'ADMIN_CUSTOMERS_SUCCESS',    
}
export const adminAllOrdersConstant = {
    ADMIN_ALLORDERS_REQUEST:'ADMIN_ALLORDERS_REQUEST',
    ADMIN_ALLORDERS_FAILURE:'ADMIN_ALLORDERS_FAILURE',
    ADMIN_ALLORDERS_SUCCESS:'ADMIN_ALLORDERS_SUCCESS',    
}

export const adminAllCategoryConstant = {
    ADMIN_CATEGORY_REQUEST:'ADMIN_CATEGORY_REQUEST',
    ADMIN_CATEGORY_FAILURE:'ADMIN_CATEGORY_FAILURE',
    ADMIN_CATEGORY_SUCCESS:'ADMIN_CATEGORY_SUCCESS',    
}

export const adminAllCategoryParentConstant = {
    ADMIN_ALL_CATEGORY_REQUEST:'ADMIN_ALL_CATEGORY_REQUEST',
    ADMIN_ALL_CATEGORY_FAILURE:'ADMIN_ALL_CATEGORY_FAILURE',
    ADMIN_ALL_CATEGORY_SUCCESS:'ADMIN_ALL_CATEGORY_SUCCESS',    
}


export const adminAllProductConstant = {
    ADMIN_PRODUCTS_REQUEST:'ADMIN_PRODUCTS_REQUEST',
    ADMIN_PRODUCTS_FAILURE:'ADMIN_PRODUCTS_FAILURE',
    ADMIN_PRODUCTS_SUCCESS:'ADMIN_PRODUCTS_SUCCESS',    
}

export const getUserOrdersConstant = {
    USER_ORDERS_REQUEST:'USER_ORDERS_REQUEST',
    USER_ORDERS_FAILURE:'USER_ORDERS_FAILURE',
    USER_ORDERS_SUCCESS:'USER_ORDERS_SUCCESS',    
}
export const setPageConstant = {
    PAGE_REQUEST:'PAGE_REQUEST',
    PAGE_FAILURE:'PAGE_FAILURE',
    PAGE_SUCCESS:'PAGE_SUCCESS',    
}

export const googleLoginConstant = {
    GOOGLE_LOGIN_REQUEST:'GOOGLE_LOGIN_REQUEST',
    GOOGLE_LOGIN_FAILURE:'GOOGLE_LOGIN_FAILURE',
    GOOGLE_LOGIN_SUCCESS:'GOOGLE_LOGIN_SUCCESS',    
}

export const changeStatusConstant = {
    CHANGE_STATUS_REQUEST:'CHANGE_STATUS_REQUEST',
    CHANGE_STATUS_FAILURE:'CHANGE_STATUS_FAILURE',
    CHANGE_STATUS_SUCCESS:'CHANGE_STATUS_SUCCESS',    
}

export const createCouponConstant = {
    CREATE_COUPON_REQUEST:'CREATE_COUPON_REQUEST',
    CREATE_COUPON_FAILURE:'CREATE_COUPON_FAILURE',
    CREATE_COUPON_SUCCESS:'CREATE_COUPON_SUCCESS',    
}

export const deleteCouponConstant = {
    DELETE_COUPON_REQUEST:'DELETE_COUPON_REQUEST',
    DELETE_COUPON_FAILURE:'DELETE_COUPON_FAILURE',
    DELETE_COUPON_SUCCESS:'DELETE_COUPON_SUCCESS',    
}

export const getCouponConstant = {
    GET_COUPON_REQUEST:'GET_COUPON_REQUEST',
    GET_COUPON_FAILURE:'GET_COUPON_FAILURE',
    GET_COUPON_SUCCESS:'GET_COUPON_SUCCESS',    
}


export const createAttributeConstant = {
    CREATE_ATTRIBUTE_REQUEST:'CREATE_ATTRIBUTE_REQUEST',
    CREATE_ATTRIBUTE_FAILURE:'CREATE_ATTRIBUTE_FAILURE',
    CREATE_ATTRIBUTE_SUCCESS:'CREATE_ATTRIBUTE_SUCCESS',    
}

export const deleteAttributeConstant = {
    DELETE_ATTRIBUTE_REQUEST:'DELETE_ATTRIBUTE_REQUEST',
    DELETE_ATTRIBUTE_FAILURE:'DELETE_ATTRIBUTE_FAILURE',
    DELETE_ATTRIBUTE_SUCCESS:'DELETE_ATTRIBUTE_SUCCESS',    
}

export const getAttributeConstant = {
    GET_ATTRIBUTE_REQUEST:'GET_ATTRIBUTE_REQUEST',
    GET_ATTRIBUTE_FAILURE:'GET_ATTRIBUTE_FAILURE',
    GET_ATTRIBUTE_SUCCESS:'GET_ATTRIBUTE_SUCCESS',    
}


export const createGiftBoxConstant = {
    CREATE_GIFTBOX_REQUEST:'CREATE_GIFTBOX_REQUEST',
    CREATE_GIFTBOX_FAILURE:'CREATE_GIFTBOX_FAILURE',
    CREATE_GIFTBOX_SUCCESS:'CREATE_GIFTBOX_SUCCESS',    
}

export const deleteGiftBoxConstant = {
    DELETE_GIFTBOX_REQUEST:'DELETE_GIFTBOX_REQUEST',
    DELETE_GIFTBOX_FAILURE:'DELETE_GIFTBOX_FAILURE',
    DELETE_GIFTBOX_SUCCESS:'DELETE_GIFTBOX_SUCCESS',    
}

export const getGiftBoxConstant = {
    GET_GIFTBOX_REQUEST:'GET_GIFTBOX_REQUEST',
    GET_GIFTBOX_FAILURE:'GET_GIFTBOX_FAILURE',
    GET_GIFTBOX_SUCCESS:'GET_GIFTBOX_SUCCESS',    
}

export const createGiftCardConstant = {
    CREATE_GIFTCARDS_REQUEST:'CREATE_GIFTCARDS_REQUEST',
    CREATE_GIFTCARDS_FAILURE:'CREATE_GIFTCARDS_FAILURE',
    CREATE_GIFTCARDS_SUCCESS:'CREATE_GIFTCARDS_SUCCESS',    
}

export const deleteGiftCardConstant = {
    DELETE_GIFTCARDS_REQUEST:'DELETE_GIFTCARDS_REQUEST',
    DELETE_GIFTCARDS_FAILURE:'DELETE_GIFTCARDS_FAILURE',
    DELETE_GIFTCARDS_SUCCESS:'DELETE_GIFTCARDS_SUCCESS',    
}

export const getGiftCardConstant = {
    GET_GIFTCARDS_REQUEST:'GET_GIFTCARDS_REQUEST',
    GET_GIFTCARDS_FAILURE:'GET_GIFTCARDS_FAILURE',
    GET_GIFTCARDS_SUCCESS:'GET_GIFTCARDS_SUCCESS',    
}

export const adminDashboardConstant = {
    ADMIN_DASHBOARD_REQUEST:'ADMIN_DASHBOARD_REQUEST',
    ADMIN_DASHBOARD_FAILURE:'ADMIN_DASHBOARD_FAILURE',
    ADMIN_DASHBOARD_SUCCESS:'ADMIN_DASHBOARD_SUCCESS',    
}

export const updateAdminConstant = {
    UPDATE_ADMIN_REQUEST:'UPDATE_ADMIN_REQUEST',
    UPDATE_ADMIN_FAILURE:'UPDATE_ADMIN_FAILURE',
    UPDATE_ADMIN_SUCCESS:'UPDATE_ADMIN_SUCCESS',    
}

export const updateAdminAvatarConstant = {
    UPDATE_ADMIN_AVATAR_REQUEST:'UPDATE_ADMIN_AVATAR_REQUEST',
    UPDATE_ADMIN_AVATAR_FAILURE:'UPDATE_ADMIN_AVATAR_FAILURE',
    UPDATE_ADMIN_AVATAR_SUCCESS:'UPDATE_ADMIN_AVATAR_SUCCESS',    
}

export const getNotificationsConstant = {
    GET_NOTIFICATION_REQUEST:'GET_NOTIFICATION_REQUEST',
    GET_NOTIFICATION_FAILURE:'GET_NOTIFICATION_FAILURE',
    GET_NOTIFICATION_SUCCESS:'GET_NOTIFICATION_SUCCESS',    
}

export const deleteNotificationsConstant = {
    DELETE_NOTIFICATION_REQUEST:'DELETE_NOTIFICATION_REQUEST',
    DELETE_NOTIFICATION_FAILURE:'DELETE_NOTIFICATION_FAILURE',
    DELETE_NOTIFICATION_SUCCESS:'DELETE_NOTIFICATION_SUCCESS',    
}